apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: fastapi
spec:
  selector:
    app: redis-master
  ports:
  - port: 6379
    targetPort: 6379